### ISSUE TITLE
text-center class too generic

### ISSUE THREAD

**Issue by grtjn** [patrickmcelwee/ml-analytics-dashboard-ng#30]
The css has this section:

```
.text-center {
  text-align: center;
  width: 60px;
}
```

Which causes weird side-effect when you also use text-center from bootstrap. This really needs more specificity, or a different name..

**Comment by patrickmcelwee** [comment]
What file is this in? I can't find this css definition.

**Comment by grtjn** [comment]
It's both in dist/ml-analytics-dashboard-ng.css, and dist/ml-analytics-dashboard-ng.less..

**Comment by patrickmcelwee** [comment]
This was fixed in https://github.com/patrickmcelwee/ml-analytics-dashboard-ng/commit/d2a68e95ee923ad9f5a93a9ec0afedc00d34a856

Are you installing this for the first time? Maybe we need to cut a new version.

**Comment by patrickmcelwee** [comment]
I created version 2.0.0 (many breaking changes ... I probably should have waited longer before creating v1.0)

**Comment by grtjn** [comment]
I'll probably stick with 1.x for the time being, it is not very disturbing for me, and reach out to you offline about the breaking changes (when I get to a point where I can upgrade)..

**Comment by patrickmcelwee** [comment]
OK ... the most significant change is that I removed route definitions in favor of directives. It might be straightforward to upgrade: just changing the entry point to a directive rather than relying on a predefined route.

**Comment by grtjn** [comment]
I was doing that anyhow.. :)
